name: liber
version: 1.0.1
github: "AliasQli/liber"
license: BSD3
author: "Alias Qli"
maintainer: "2576814881@qq.com"
copyright: "2021 Alias Qli"

extra-source-files:
  - script.scr
  - src/c/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/AliasQli/liber#readme>

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - containers
  - text
  - filepath
  - bytestring
  - word8
  - recursion-schemes
  - template-haskell
  - mtl
  - vector
  - megaparsec
  - hspec-megaparsec
  - raw-strings-qq
  - binary
  - lens
  - time
  - directory
  # - encoding

ghc-options:
  - -j
  - -O
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  # - -Wredundant-constraints
  - -Wno-orphans
  - -Wno-name-shadowing

default-extensions:
  - ApplicativeDo
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

library:
  source-dirs: src

executables:
  # liber-embedded:
  #   main:                Main.hs
  #   source-dirs:         embedded
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   - src/c/terminal.c
  #   dependencies:
  #   - liber
  main:
    main: Main.hs
    source-dirs: main
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - src/c/terminal.c
    dependencies:
      - liber
  encoder:
    main: Main.hs
    source-dirs: encoder
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - liber
  

tests:
  liber-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - liber
