name:                liber
version:             1.0.0.0
github:              "Alias Qli/liber"
license:             BSD3
author:              "Alias Qli"
maintainer:          "2576814881@qq.com"
copyright:           "2021 Alias Qli"

extra-source-files:
- script.scr
- src/c/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Alias Qli/liber#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
# - file-embed
- text
- filepath
- bytestring
- word8
- recursion-schemes
- template-haskell
- mtl
- vector

library:
  source-dirs: src

executables:
  liber-embedded:
    main:                Main.hs
    source-dirs:         embedded
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - src/c/terminal.c
    dependencies:
    - liber
  liber-standalone:
    main:                Main.hs
    source-dirs:         standalone
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - src/c/terminal.c
    dependencies:
    - liber

tests:
  liber-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    # -with-rtsopts=-N
    dependencies:
    - liber
